### ISSUE TITLE
Tolk not in requirements

### ISSUE THREAD

**Issue by braillescreen** [masonasons/Quinter#1]
Hello,
Would like to first say I love how the code is layed out, I actually feel like I can understand this LOL.
Secondly, I just wanted to note here that Tolk isn't in the requirements file.

**Comment by trypsynth** [comment]
Hi, it doesn't need to be. Tolk.py is right inside the directory. Is Tolk actually on Pypi?

**Comment by braillescreen** [comment]
No, apparently not. I just get the following when trying to run Quinter.
Will include the entire error.
```
Traceback (most recent call last):
  File "quinter.pyw", line 16, in <module>
    import speak
  File "C:\Users\Owner\Dropbox\git\quinter\speak.py", line 6, in <module>
    import Tolk as speaker
  File "C:\Users\Owner\Dropbox\git\quinter\Tolk.py", line 11, in <module>
    _tolk = cdll.Tolk
  File "I:\python\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "I:\python\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'Tolk' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by trypsynth** [comment]
Ah. I see your issue. You need to be using Python 3.7 or below. 3.8 and above horribly break Tolk's method of loading the DLL for some reason. I should probably add a venv so you can use py 3.7 without needing to reinstall, but have no idea how they work

**Comment by braillescreen** [comment]
Ah. Thanks.

**Comment by trypsynth** [comment]
OK, I've just pushed a change aiming to fix this. Does it work now?

**Comment by trypsynth** [comment]
Have gotten confirmation that it works, so closing this.
