### ISSUE TITLE
DM buffer shouldn't announce for sent messages

### ISSUE THREAD

**Issue by KevanGP** [masonasons/Quinter#12]
Hi,

When I send a direct message, it gets put into the DM timeline/buffer with received messages. This is a bit annoying, as the sound for DMs goes off because of the new buffer item. This isn't necessary, I think sent DMs should get put into their own buffer to resolve this problem. I'm able to mute the sent tweet buffer, but don't want to mute the DM buffer because then I'll miss received DMs as well.

Can you please do something about this annoyance? It's not a huge deal but is bothersome enough to deserve a bug report.

**Comment by trypsynth** [comment]
I disagree. This makes it much easier to keep up with the conversation, rather than having to switch between two different buffers. @Masonasons, thoughts?

**Comment by masonasons** [comment]
I disagree as well.

**Comment by KevanGP** [comment]
True, but can you make a way to turn off the sound of the buffer updating for sent DMs?

**Comment by trypsynth** [comment]
We probably could, but it's more effert than it's worth. Plus, we could have the same argument about home. When sending a tweet, you get it in your home buffer and hear the sound. Why should direct messages be any different?

**Comment by KevanGP** [comment]
I can mute the home buffer, and usually have it muted. Same with the sent buffer.
The DM thing will take some getting used to, a few times I heard the DM sound, went to check my new message, and realized it was only a sent message.
