### ISSUE TITLE
Suggestion: if only one URL is present, open it instead of prompting the user to choose

### ISSUE THREAD

**Issue by mehgcap** [masonasons/Quinter#13]
As the title says, I'd like to suggest that the user not have to choose from a list of URLs in a tweet. If the user presses alt-win-enter (or whatever the UI equivalent is), a dialog appears, prompting them to choose a URL. If there's only one URL in the tweet, this step should be skipped, and that URL should open immediately.

**Comment by mehgcap** [comment]
I have successfully implemented this feature. I did so on my fork, in a branch named "issue13". How would you like me to proceed, assuming you want this feature to be added?

**Comment by masonasons** [comment]
Hi Alex,

Please be sure of the following. Please implement for this to be a toggle. I personally would want to see the URL I'm opening, even if it's just a single URL. This way, for dropbox URRL's specifically, I can alter a dl=0 to a dl=1 if I need to, etc. I like your idea though and can't wait to get this merged!

Files of note to make this happen are GUI/options.py, and globals.py for preferences initialization. I.E. you have to make a preference in globals.py first, then observe the options.py file for how options are added and stored and such. If you need any help, glad to assist!

**Comment by mehgcap** [comment]
I believe this is complete. My checkbox is in the globals > general dialog, it shows the correct state, I believe it persists, and--of course--if it is unchecked, the choose dialog appears even for a single URL in a tweet.
