### ISSUE TITLE
Possible readme rewrite?

### ISSUE THREAD

**Issue by trypsynth** [masonasons/Quinter#16]
As this would be a pretty big change to how the users see the docs, I figured I'd open an issue first. I was considering rewriting the docs in Markdown and converting to nicely readable HTML with Pandoc. This would
* Give us a table of contents
* Make users able to jump to different sections by heading level.
* Keep the readme in an easy-to-understand format.
Thoughts?

**Comment by masonasons** [comment]
If you want to do it, bee my guest.

**Comment by trypsynth** [comment]
OK, sweet.
