### ISSUE TITLE
Feature request: Ability to upload audio

### ISSUE THREAD

**Issue by KevanGP** [masonasons/Quinter#17]
Can you please add for Quinter the the ability to record/upload audio clips to SndUp.net? It already has the ability to play them.
If Twitter's API doesn't allow external clients working with Twitter spaces and voice recordings, Quinter should support the next best thing in my humble opinion.

**Comment by masonasons** [comment]
No.

**Comment by KevanGP** [comment]
Why not?

**Comment by trypsynth** [comment]
Because there's no point. You can just share a dropbox link or an SNDUp link.
