### ISSUE TITLE
the unblock command generates no client output but does throw a juicy entry in the log.

### ISSUE THREAD

**Issue by stickbear2015** [masonasons/Quinter#18]
If you press ctrl+shift+b, or access the unblock feature from the user menu, you get no client output, but the error log as of version 0.61 stable, as well as 0.62 source release chucks the following.
stable version
Traceback (most recent call last):
  File "D:\portable installs\Quinter-stable\GUI\main.py", line 551, in OnUnblock
AttributeError: module 'globals' has no attribute 'current_account'
source release
Traceback (most recent call last):
  File "D:\portable installs\Quinter-unstable\GUI\main.py", line 551, in OnUnblock
AttributeError: module 'globals' has no attribute 'current_account'
Yup, it is most certainly broken. :)

**Comment by trypsynth** [comment]
Oooh! I think I know the problem. I swore I'd sleep hours ago, and will have very little free time for the next few days though. CC @masonasons

**Comment by trypsynth** [comment]
Hi,
Can you try with the latest source and let me know if it works now? Thanks!

**Comment by stickbear2015** [comment]
commit 2c7623eef753089fc200ffe3c10be70b74eeca3f fixes this nicely, I'm closing as successfully fixed.
