### ISSUE TITLE
Allow Quinter to display times in 24-hour time

### ISSUE THREAD

**Issue by braillescreen** [masonasons/Quinter#19]
I am not sure if displaying 24-hour time is possible since the readme says relative timestamps might be hard to display, but it'd be awesome if we could have 24-hour time somewhere as that's typically how I use Twitter on every other device.

**Comment by mehgcap** [comment]
I have implemented this as a user preference. I'll make a PR.

**Comment by trypsynth** [comment]
Closing, as #21 has been merged and works great! :)

**Comment by trypsynth** [comment]
@mehgcap, it seems your pull request broke time stamps. If something happened before today, it shows the time as if it happened today. Can you fix this please?
