### ISSUE TITLE
Incorrect count of characters when composing a tweet

### ISSUE THREAD

**Issue by riku22** [masonasons/Quinter#2]
Hello.

If you enter characters that include multi-byte characters such as Japanese when composing a tweet, the characters that should be counted as 2 characters are counted as 1 character.
Is it possible to calculate the correct number of characters with "twitter-text-parser" etc.?

**Comment by trypsynth** [comment]
I think this is the fault of the wx.TextCtrl object. Not sure of much we can do about it. If you have information I don't though, feel free to share/open a PR. :)

**Comment by trypsynth** [comment]
Closing, because #4 fixed it.
