### ISSUE TITLE
Problems with compiling Quinter

### ISSUE THREAD

**Issue by seedy60** [masonasons/Quinter#26]
Quinter is throwing errors when I try to run the executable file after compiling. To show that I'm doing everything right, here's a list of the steps I'm going through.

1. Run pip install -r requirements.txt to install the required dependencies. This works as expected, and the requirements install successfully.
2. Test Quinter by executing run.bat. Quinter fires up no problem. No errors, everything works fine.
3. After testing to see if Quinter works, run build.bat to start the compilation process.
4. After compilation is complete, run copy.bat.
5. CD into the windist folder created by copy.bat, and run Quinter.exe. Quinter throws an error here; something to do with the sound_lib module.
See the attached error log file.
[errors.log](https://github.com/QuinterApp/Quinter/files/7045551/errors.log)

**Comment by trypsynth** [comment]
You need all the sound_lib DLLs. Copy.bat might not do them if you don't have your directory set up like we do. If you have sound_lib installed, go into your sight packages, grab the lib folder, put it inside a folder called sound_lib where you built quinter, and it should work.

**Comment by seedy60** [comment]
If I don't have my directory set up like you do?
