### ISSUE TITLE
problems building quinter on mac

### ISSUE THREAD

**Issue by simteraplications** [masonasons/Quinter#28]
Hi. I have been trying to build quinter on my m1 mac but have ran into trouble. Problem is simple. The included text file sais i should delete the x86 folder and replace the x64 folder with the one in m1 files. Problem, theres no folder named m1 files. Neither in quinter it self or in the linked sound-lib. What do i do to find these files?

**Comment by trypsynth** [comment]
The building Quinter on m1 thing actually never worked fully, and that file was included just... Cuz I guess. I think you'd need Arm Bass Dylib files, and that's it. But I've had nothing but issues building Quinter natively on M1. WxPython only recently got an M1 build, and it's still breaky.

**Comment by simteraplications** [comment]
And let me guess. That is not even a thing yet? Adleast google doesn't pull up any thing usefull, but that is nothing rare to happen with these libs so are there m1 versions?
