### ISSUE TITLE
Feature request: Move the timeline significantly

### ISSUE THREAD

**Issue by riku22** [masonasons/Quinter#8]
Would you please add a key to move items back and forth by 10 or 20 items in invisible interface?
If possible, I would be grateful if you could consider it.

**Comment by trypsynth** [comment]
So, what you're thinking is sort of like what pressing page up/down does in the GUI, but for the invisible interface?

**Comment by riku22** [comment]
I think Alt + Windows + PageUp/Down is good.
However, in this case, you need to assign the existing Alt + Windows + PageUp command to another key.

**Comment by trypsynth** [comment]
Hi,
Yes, I was more asking about what you wanted the key to do.

**Comment by riku22** [comment]
Hi.
In the GUI, you can skip some items with PageUp and PageDown, but you can't do that with the invisible interface, and you can only move one item at a time, which is inconvenient.
I'm sorry if I don't understand the intent of the question.

**Comment by trypsynth** [comment]
Ah, yeah, so you are suggesting what I thought. How much do you think would be a good amount? Because the page up/page down thing isn't actually anything we're doing, it's the GUI library.

**Comment by riku22** [comment]
There are 20 items in another app "TW Blue", so maybe 20 items are good.

**Comment by masonasons** [comment]
@riku22 Try this out and see if it's what you are looking for.

**Comment by riku22** [comment]
Thank you.
